# Site settings
title: InJoin
baseurl: ""
timezone: America/Sao_Paulo
github_url: https://github.com/injoin/injoin.github.io

# Authors
authors:
   gustavohenke:
      name: Gustavo Henke
      email: gustavo@injoin.io
      gravatar: f46023f904309178e8d9bfc7a4a37979
      about: Web Developer na Syonet CRM e amante de desenvolvimento front-end

# Disqus config
disqus:
   name: injoinweb

# Build settings
markdown: kramdown
exclude:
   - libs

sass:
   sass_dir: styles
   style: compressed